export { default as SortIcon } from "./sort";
export { default as SearchIcon } from "./search";
export { default as FileIcon } from "./file";
export { default as ImageIcon } from "./imageIcon";
export { default as ExcelIcon } from "./excel";
export { default as PdfIcon } from "./pdf";
export { default as FavouriteIcon } from "./favourite";
export { default as DownloadIcon } from "./download";
export { default as PrintIcon } from "./print";
